apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2020-02-11T02:39:11Z"
    creationTimestamp: "2020-02-11T02:38:26Z"
    labels:
      app: database-server
      app.kubernetes.io/component: database-server
      app.kubernetes.io/instance: database-server
    name: database-server
    namespace: wildfly-demo
    resourceVersion: "76622"
    selfLink: /api/v1/namespaces/wildfly-demo/endpoints/database-server
    uid: 94499856-4c77-11ea-b029-0ef0e3c74fbe
  subsets:
  - addresses:
    - ip: 10.128.0.190
      nodeName: crc-q4zfq-master-0
      targetRef:
        kind: Pod
        name: database-server-1-q946z
        namespace: wildfly-demo
        resourceVersion: "76621"
        uid: 9ff9deee-4c77-11ea-b029-0ef0e3c74fbe
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2020-02-11T02:39:50Z"
    labels:
      app: wildfly-app
      app.kubernetes.io/component: wildfly-app
      app.kubernetes.io/instance: wildfly-app
      app.kubernetes.io/name: wildfly
    name: wildfly-app
    namespace: wildfly-demo
    resourceVersion: "78723"
    selfLink: /api/v1/namespaces/wildfly-demo/endpoints/wildfly-app
    uid: c6770a6a-4c77-11ea-b029-0ef0e3c74fbe
  subsets:
  - addresses:
    - ip: 10.128.0.193
      nodeName: crc-q4zfq-master-0
      targetRef:
        kind: Pod
        name: wildfly-app-1-scsfd
        namespace: wildfly-demo
        resourceVersion: "77770"
        uid: 67228849-4c78-11ea-b029-0ef0e3c74fbe
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
    - name: 8778-tcp
      port: 8778
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
